### ISSUE TITLE
buffer_type = "user"

### ISSUE THREAD

**Issue by AndreaSanchezTapia** [Model-R/modleR_tests#1]
O test do buffer de usuário deve ser feito com os demais parâmetros possíveis.
Tenho quase certeza de que combinar user e dist_min vai dar erro e isso precisa ser corrigido.

**Comment by Tai-Rocha** [comment]
Error in create_buffer(occurrences = occurrences, models_dir = models_dir,  : 
  object 'dist.buf' not found

O erro acontece quando o buffer user é usado com  argumento dist_min.
